name: laser_pecker
description: 2023-11-20 LaserPeckerApp
version: 0.0.1
homepage: https://github.com/angcyo/Flutter3Abc
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter3_app:
    path: ../Flutter3Core/flutter3_app
  flutter3_web:
    path: ../Flutter3Core/flutter3_web

  # https://pub.dev/packages/flutter_gen
  # https://pub.dev/packages/build_runner
  # https://pub.dev/packages/flutter_gen_runner
  flutter_gen: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: any
  flutter_gen_runner: any

# https://pub.dev/packages/flutter_gen#configuration-file
flutter_gen:
  output: lib/assets_generated/ # Optional (default: lib/gen/)
  integrations:
    #flutter_svg: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/svg/
    - assets/png/

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages

# https://pub.dev/packages/intl
# https://pub.dev/packages/intl_utils
# https://localizely.com/flutter-arb/
# flutter pub run intl_utils:generate
flutter_intl:
  enabled: true
  class_name: LPS
  main_locale: zh
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated
  use_deferred_loading: false