#!/usr/bin/env bash

# Turn off echo 关闭回显
set +x

# 将工作目录设置为脚本所在目录
# shellcheck disable=SC2164
cd "$(dirname "$0")"

# https://docs.flutter.dev/deployment/android#build-the-app-for-release
dart run Flutter3Core/script/build_config.dart & flutter build appbundle --release