#!/usr/bin/env bash

# Turn off echo 关闭回显
set +x

# 将工作目录设置为脚本所在目录
cd "$(dirname "$0")"

dart fix --dry-run

# dart fix --apply
# dart fix --apply --code=dangling_library_doc_comments
# dart fix --apply --code=deprecated_member_use
# dart fix --apply --code=no_leading_underscores_for_local_identifiers
# dart fix --apply --code=prefer_const_constructors
# dart fix --apply --code=prefer_const_declarations
# dart fix --apply --code=prefer_final_fields
# dart fix --apply --code=unnecessary_import
# dart fix --apply --code=unnecessary_overrides
# dart fix --apply --code=unused_element
# dart fix --apply --code=unused_import
# dart fix --apply --code=use_super_parameters
