#!/usr/bin/env bash

# Turn off echo 关闭回显
set +x

# 将工作目录设置为脚本所在目录
cd "$(dirname "$0")"

git fetch
git rebase origin/main

coreFolder="Flutter3Core"
if [ -d "$PWD/$coreFolder" ]; then
    cd $coreFolder
    echo "准备拉取仓库：$coreFolder"
    git fetch
    git rebase origin/main
    cd ..
else
    echo "准备克隆仓库：$coreFolder"
    git clone git@github.com:angcyo/Flutter3Core.git
fi

extendFolder="Flutter3Extend"
if [ -d "$PWD/$extendFolder" ]; then
    cd $extendFolder
    echo "准备拉取仓库：$extendFolder"
    git fetch
    git rebase origin/main
    cd ..
else
    echo "准备克隆仓库：$extendFolder"
    git clone git@github.com:angcyo/Flutter3Extend.git
fi

abcFolder="Flutter3Abc"
if [ -d "$PWD/$abcFolder" ]; then
    cd $abcFolder
    echo "准备拉取仓库：$abcFolder"
    git fetch
    git rebase origin/main
    cd ..
else
    echo "准备克隆仓库：$abcFolder"
    git clone git@github.com:angcyo/Flutter3Abc.git
fi

read -n 1 -s -r -p "!结束! Press any key to continue..."
